config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :new, :create]
  resources :sessions, only: [:show, :new, :create]
  resources :events, only: [:index, :show]

  get '/pick_users/:session_id/', to: 'sessions#pick_users', as: 'pick_users'
  get '/users_sessions/:session_id/:user_id', to: 'users_sessions#create', as: 'add_users'
  get '/users_events/:event_id/:user_id', to: 'users_events#create', as: 'register_event'

  get '/login', to: 'accounts#login'
  post '/login', to: 'accounts#process_login'
  get '/logout', to: 'accounts#logout'
  
  delete '/users_sessions/:user_id/:session_id', to: 'users_sessions#destroy', as: 'users_session'
  delete '/users_events/:event_id/:user_id', to: 'users_events#destroy', as: 'unregister_event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :users_sessions
  has_many :users_events
  has_many :sessions, through: :users_sessions
  has_many :events, through: :users_events

  has_secure_password


  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def self.search(search)
    if search
      clean_name = search.values.first.downcase.capitalize
      if search.keys.first == "first_name"
        user = User.where(first_name: clean_name)
      elsif search.keys.first == "last_name"
        user = User.where(last_name: clean_name)
      elsif search.keys.first == "full_name"
        names = clean_name.split
        last = names[1].capitalize
        user = User.where(first_name: names[0], last_name: last)
      elsif search.keys.first == "username"
        user = User.where(username: search[:username])
      end
    else
      return User.all
    end
  end

  def total_distance
    self.sessions.map{|session| session.distance}.sum.round(2)
  end

  def total_duration
    self.sessions.map{|session| session.duration}.sum.round(2)
  end

  def display_total_duration
    if total_duration >= 60
      hours = (total_duration / 60)
      minutes = ((hours % 1) * 60).to_i
      "#{hours.to_i} hours #{minutes} minutes"
    else
      "#{total_duration.to_i} minutes"
    end
  end

  ## returns average pace of all sessions minutes per mile
  def average_pace
    if self.total_distance == 0
      "You have no sessions yet"
    else
      raw_pace = self.total_duration / self.total_distance

      minutes = raw_pace.to_i
      seconds = ((raw_pace % 1) *60).to_i

      formatted_pace = "#{minutes}\'#{seconds}\""
    end
  end

  def events_eligible
    events = Event.all
    eligible = events.select{|event| self.total_distance >= event.min_miles_run && !self.events_registered.include?(event)}
  end

  def events_registered
    self.events
  end

  def friends
    @sessions = self.sessions
    friends = []
    @sessions.each{|session|
      session.users.each {|user| friends << user}}
    friends.delete(self)
    friends.uniq
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, except: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events_eligible
    @registered = @user.events_registered
    @friends = @user.friends
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.full_name, user_path(user) %> </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br><br>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br><br>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br><br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br><br>

  <%= f.label :password_confirmation, "Confirm Password"  %>
  <%= f.password_field :password_confirmation %>
  <br><br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="user_show_header">
  <h1>Details for <%= @user.full_name %></h1>
</div>

<div class="row">
  <div class="container user_stats">
    <h2>Stats</h2>
    <h4>Total Distance Run:</h4>
    <p><%= "#{@user.total_distance} Miles"%></p>
    <h4>Total Time Run: </h4>
    <p><%= @user.display_total_duration%></p>
    <h4>Average Pace: </h4>
    <p><%= @user.average_pace%>/ mile</p>
    <h4>Number of Sessions:</h4>
    <p><%= "#{@user.sessions.count} Practice Sessions"%></p>
  </div>

  
  <div class="container user_sessions">
    <h2><%= @user.full_name %>'s Sessions</h2>
    
    <ul>
      <% @user.sessions.each do |session| %>
        <div><%= link_to "#{session.start_time.strftime("%A, %B %d, %Y")} beginning at #{session.start_time.strftime("%I:%M%p")}", session_path(session) %> 
        <%if current_user.id == @user.id%>
          <button type="button" class="btn btn-outline-danger"><%= link_to "Remove this Session from My Sessions", users_session_path(@user, session), method: :delete%></button>
        <%end%>
        </div>
      <% end %>
    </ul>
  
    <%if current_user.id == @user.id%>
      <button type="button" class="btn btn-warning"><%= link_to "Create a new session", new_session_path %></button>
    <%end%>
  </div>
</div>

<div class="row">
    <div class="container friends">
    <h2>Here are your Run Buddies!</h2>
    <% @friends.each do |friend|%>
    <li><%= link_to friend.full_name, user_path(friend)%></li>
    <%end%>
  </div>
  </div>

<div class="row">
  <div class="container eligible_events">
    <h2>Events Eligible For: </h2>
  
    <%@events.each do |event|%>
      <li><%= link_to event.name, event_path(event)%></li>
    <%end%>
  </div>
  
  <div class="container registered_events">
    <h2>Events Registered For: </h2>
  
    <%@registered.each do |event|%>
      <li><%= link_to event.name, event_path(event)%></li>
    <%end%>
  </div>
</div>