config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :new, :create]
  resources :sessions, only: [:show, :new, :create]
  resources :events, only: [:index, :show]

  get '/pick_users/:session_id/', to: 'sessions#pick_users', as: 'pick_users'
  get '/users_sessions/:session_id/:user_id', to: 'users_sessions#create', as: 'add_users'
  get '/users_events/:event_id/:user_id', to: 'users_events#create', as: 'register_event'

  get '/login', to: 'accounts#login'
  post '/login', to: 'accounts#process_login'
  get '/logout', to: 'accounts#logout'
  
  delete '/users_sessions/:user_id/:session_id', to: 'users_sessions#destroy', as: 'users_session'
  delete '/users_events/:event_id/:user_id', to: 'users_events#destroy', as: 'unregister_event'
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :users_events
    has_many :users, through: :users_events

    def self.search(search)
        if search
            if search.keys.first == "name"
                events = Event.where(name: search[:name])
            elsif search.keys.first == "min_miles_run"
                events = Event.where("min_miles_run >= ? ", search.values.first)
            elsif search.keys.first == "max_distance"
                events = Event.where("distance <= ?", search.values.first)
            elsif search.keys.first == "min_distance"
                events = Event.where("distance >= ?", search.values.first)
            end
        else
          return Event.all
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    

    def index
        if params.keys.include?("search")
            return @events = Event.search(params[:search])
        else
            return @events = Event.all
        end
    end

    def show
        @event = Event.find(params[:id])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<h4>Search for Events By:</h4>
   <%= form_tag(events_path, method: :get) do %>
      Name: <%= text_field_tag("search[name]")%>
      <%= submit_tag ("Search")%><br>
      <%end%>
    <%= form_tag(events_path, method: :get) do %>
      Min. Miles Run Required: <%= text_field_tag("search[min_miles_run]")%>
      <%= submit_tag ("Search")%><br>
      <%end%>
    <%= form_tag(events_path, method: :get) do %>
      Distance of Event (Maximum): <%= text_field_tag("search[max_distance]")%>
      <%= submit_tag ("Search")%><br>
      <%end%>
    <%= form_tag(events_path, method: :get) do %>
      Distance of Event (Minimum): <%= text_field_tag("search[min_distance]")%>
      <%= submit_tag ("Search")%><br>
      <%end%>


<ul>
    <% @events.each do |event| %>
        <li><%= link_to event.name, event_path(event)%></li>
    <%end%>
</ul>

app/views/events/show.html.erb
<h1><%=@event.name%></h1>

<h2>Event Details:</h2>
<h4>Location:</h4>
<p><%= @event.location%></p>
<h4>Date:</h4>
<p><%= @event.date%></p>
<h4>Distance:</h4>
<p><%= @event.distance%> miles</p>



<h2>Minimum Requirements to Qualify:</h2>
<h4>Minimum Number of Practice Sessions: <%=@event.min_num_of_sessions%></h4>
<h4>Minimum Number of Miles Run: <%=@event.min_miles_run%></h4>

<h2><%= pluralize(@event.users.count, 'Participant')%>: </h2>
<%@event.users.each do |user|%>
<li><%= link_to user.full_name, user_path(user)%></li>
<%end%>


<% if current_user.events_eligible.include?(@event) || current_user.events_registered.include?(@event)%>
    <%if @event.users.include?(current_user)%>
    <button type="button" class="btn btn-danger"><%= link_to "Unregister for this Event", unregister_event_path(@event, current_user), method: :delete%></button>
    <%else%>
<button type="button" class="btn btn-success"><%= link_to "Register for this Event", register_event_path(@event, current_user)%></button>
<%end%>
<%end%>