config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :new, :create]
  resources :sessions, only: [:show, :new, :create]
  resources :events, only: [:index, :show]

  get '/pick_users/:session_id/', to: 'sessions#pick_users', as: 'pick_users'
  get '/users_sessions/:session_id/:user_id', to: 'users_sessions#create', as: 'add_users'
  get '/users_events/:event_id/:user_id', to: 'users_events#create', as: 'register_event'

  get '/login', to: 'accounts#login'
  post '/login', to: 'accounts#process_login'
  get '/logout', to: 'accounts#logout'
  
  delete '/users_sessions/:user_id/:session_id', to: 'users_sessions#destroy', as: 'users_session'
  delete '/users_events/:event_id/:user_id', to: 'users_events#destroy', as: 'unregister_event'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%# Bootstrap CSS %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <% if logged_in? %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    
      <a class="navbar-brand" href="#">
        <% if current_user %>
          <div>Welcome, <%= current_user.first_name %></div>
        <% end %>
      </a>

      <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> %>

      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav">

          <li class="nav-item active">
            <%= link_to "My Profile", user_path(current_user), class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "All Users", users_path, class: "nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Events", events_path, class: "nav-link"%>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="/logout" class="nav-link">Log out</a>
            <%#= link_to "Logout", logout_path %>
          </li>
        </ul>

      </div>
    </nav>
  <% end %>

 

    <% if notice %>
      <div class="notice">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>

    <%# JavaScript %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>